### ISSUE TITLE
CountDown 倒计时 

### ISSUE THREAD

**Issue by douxihe** [zhhyang/yep-react#57]
class Home extends PureComponent<IMyDetailProps, IMyDetailState> {
  constructor(props: IMyDetailProps) {
    super(props);
    this.state = {
      seconds: 10,
      voteCount: 10
    };
  }
  async componentWillMount() {
    let paramInfo = {
      activityGroupId: 'vote2020083101'
    };
    const res = await Service.getFindVoteInfo(paramInfo);
    console.log(res);
    this.setState({
      seconds: res.seconds,
      voteCount: res.voteCount
    });
  }
  render() {
      const { seconds } = this.state;
    return (
      <div>
        {seconds}
        {
            seconds !== 10 && 
            <CountDown leftTime={seconds}>
                {/* {({dayStr, hourStr, minuteStr, secondStr}) => (
                    <p>
                    倒计时剩余： {dayStr}天{hourStr}小时{minuteStr}分钟{secondStr}秒
                    </p>
                )} */}
            </CountDown>
        }
        <div>{this.state.voteCount}</div>
      </div>
    );
  }
}
通过接口改值的话，组件不会render，只好加了个判断

**Comment by zhhyang** [comment]
因为没有考虑数据变化的场景，所以需要判断已经拿到倒计时数据的情况下渲染组件
